# Generated by Django 5.1.1 on 2024-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('id_trabajador', models.PositiveIntegerField()),
                ('id_troca', models.PositiveIntegerField()),
                ('ganancias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_de_pago', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
